# cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders'
  args: ['npm', 'install']
- name: 'gcr.io/cloud-builders'
  args: ['npm', 'run', 'build']
- name: 'gcr.io/cloud-builders'
  args: ['npm', 'run', 'deploy']